export default [
  {
    id: 1,
    img: {
      src: "https://scrimba.com/links/travel-journal-japan-image-url",
      alt: "Mount Fuji",
    },
    title: "Mount Fuji",
    country: "Japan",
    googleMapsLink: "https://maps.app.goo.gl/6RLYZDuuuqJ7kNGZ9",
    dates: "12 Jan, 2021 - 24 Jan, 2021",
    text: "Mount Fuji is the tallest mountain in Japan, standing at 3,776 meters (12,380 feet). Mount Fuji is the single most popular tourist site in Japan, for both Japanese and foreign tourists.",
  },
  {
    id: 2,
    img: {
      src: "https://scrimba.com/links/travel-journal-australia-image-url",
      alt: "Sydney Opera House",
    },
    title: "Sydney Opera House",
    country: "Australia",
    googleMapsLink: "https://maps.app.goo.gl/Zr17SCrsJeCEKMd36",
    dates: "27 May, 2021 - 8 Jun, 2021",
    text: "The Sydney Opera House is a renowned performing arts center in Sydney, celebrated as a masterpiece of 20th-century architecture and one of the world's most iconic buildings.",
  },
  {
    id: 3,
    img: {
      src: "https://scrimba.com/links/travel-journal-norway-image-url",
      alt: "Geirangerfjord",
    },
    title: "Geirangerfjord",
    country: "Norway",
    googleMapsLink: "https://maps.app.goo.gl/fhkJuBhmFDv47tiB7",
    dates: "01 Oct, 2021 - 18 Nov, 2021",
    text: "The Geiranger Fjord is a fjord in the Sunnmøre region of Møre og Romsdal county, Norway. It is located entirely in the Stranda Municipality.",
  },
  {
    id: 4,
    img: {
      src: "https://www.savaari.com/blog/wp-content/uploads/2023/08/A_river_sight_from_Gurez-Tulail_Valley1.webp",
      alt: "Gurez Valley",
    },
    title: "Gurez Valley",
    country: "India",
    googleMapsLink: "https://maps.app.goo.gl/igHpxTbVURdrEBh48",
    dates: "15 Apr, 2022 - 25 Apr, 2022",
    text: "Gurez Valley, located in the high Himalayas of Jammu and Kashmir, is a serene and picturesque destination, offering breathtaking views of snow-capped peaks and lush landscapes.",
  },
  {
    id: 5,
    img: {
      src: "https://www.onacheaptrip.com/wp-content/uploads/Amazing-scenes-at-Ziro-Valley-Arunachal-Pradesh.jpg",
      alt: "Ziro Valley",
    },
    title: "Ziro Valley",
    country: "India",
    googleMapsLink: "https://maps.app.goo.gl/gB8ZpKy2gdJLm5Zf9",
    dates: "05 Jun, 2022 - 15 Jun, 2022",
    text: "Ziro Valley in Arunachal Pradesh is a tranquil haven, surrounded by pine-clad hills and rice fields, and home to the unique Apatani tribal culture.",
  },
  {
    id: 6,
    img: {
      src: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/54/Dawki_River%2C_Meghalaya.jpg/1200px-Dawki_River%2C_Meghalaya.jpg?20220112032603",
      alt: "Dawki River",
    },
    title: "Dawki River",
    country: "India",
    googleMapsLink: "https://maps.app.goo.gl/NxjmAAC9ughFxhR19",
    dates: "20 Jul, 2022 - 30 Jul, 2022",
    text: "Dawki, located in Meghalaya, is renowned for its crystal-clear Umngot River, offering mesmerizing boat rides where the boats appear to float on air.",
  },
  {
    id: 7,
    img: {
      src: "https://plus.unsplash.com/premium_photo-1732737296420-02aca47b8f4a?w=1000&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTN8fFRhd2FuZyUyME1vbmFzdGVyeXxlbnwwfHwwfHx8MA%3D%3D",
      alt: "Tawang Monastery",
    },
    title: "Tawang Monastery",
    country: "India",
    googleMapsLink: "https://maps.app.goo.gl/AJBrhiDCtFkwN65J8",
    dates: "01 Sep, 2022 - 10 Sep, 2022",
    text: "Tawang Monastery in Arunachal Pradesh is the largest monastery in India, perched atop a hill, offering spiritual solace amidst stunning Himalayan vistas.",
  },
  {
    id: 8,
    img: {
      src: "https://iastoppers.com/landing/wp-content/uploads/2024/02/Loktak-Manipur.jpg",
      alt: "Loktak Lake",
    },
    title: "Loktak Lake",
    country: "India",
    googleMapsLink: "https://maps.app.goo.gl/fJxxecqYurmLgvK49",
    dates: "15 Oct, 2022 - 25 Oct, 2022",
    text: "Loktak Lake in Manipur is the largest freshwater lake in northeastern India, famous for its phumdis (floating islands) and rich biodiversity.",
  },
  {
    id: 9,
    img: {
      src: "https://images.unsplash.com/photo-1709624521616-e4fc3089aca7?w=1000&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8U2FuZGFrcGh1JTIwUGVha3xlbnwwfHwwfHx8MA%3D%3D",
      alt: "Sandakphu Peak",
    },
    title: "Sandakphu Peak",
    country: "India",
    googleMapsLink: "https://maps.app.goo.gl/Kgvnu6688Kwesx1c9",
    dates: "01 Nov, 2022 - 10 Nov, 2022",
    text: "Sandakphu, the highest peak in West Bengal, offers panoramic views of four of the world's five highest peaks, making it a trekker's paradise.",
  },
  {
    id: 10,
    img: {
      src: "https://images.unsplash.com/photo-1542709111240-e9df0dd813b4?w=1000&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8ZHp1a291JTIwdmFsbGV5fGVufDB8fDB8fHww",
      alt: "Dzukou Valley",
    },
    title: "Dzukou Valley",
    country: "India",
    googleMapsLink: "https://maps.app.goo.gl/f6NaMo9CVfpkRh3PA",
    dates: "15 Dec, 2022 - 25 Dec, 2022",
    text: "Dzukou Valley, straddling the border of Nagaland and Manipur, is known for its rolling hills, lush greenery, and the rare Dzukou lily.",
  },
  {
    id: 11,
    img: {
      src: "https://images.unsplash.com/photo-1572333837703-3f5d7a24c714?w=1000&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8R2FuZGlrb3RhJTIwQ2FueW9ufGVufDB8fDB8fHww",
      alt: "Gandikota Canyon",
    },
    title: "Gandikota Canyon",
    country: "India",
    googleMapsLink: "https://maps.app.goo.gl/UdW51mKh64BMmKPt7",
    dates: "05 Jan, 2023 - 15 Jan, 2023",
    text: "Gandikota, often referred to as the 'Grand Canyon of India,' is a hidden gem in Andhra Pradesh, featuring stunning gorges carved by the Pennar River.",
  },
  {
    id: 12,
    img: {
      src: "https://i.pinimg.com/736x/b7/e7/b2/b7e7b2fc11b2121ba7fb48cc05d43a65.jpg",
      alt: "Haflong Hill",
    },
    title: "Haflong Hill",
    country: "India",
    googleMapsLink: "https://maps.app.goo.gl/fy1rwwAXkkGDK1nq9",
    dates: "20 Feb, 2023 - 28 Feb, 2023",
    text: "Haflong, the only hill station in Assam, is known for its picturesque hills, serene lakes, and rich cultural heritage, making it a perfect retreat for nature enthusiasts.",
  },
  {
    id: 13,
    img: {
      src: "https://thumbs.dreamstime.com/b/pine-tree-forest-trees-267063993.jpg?w=768",
      alt: "Lepchajagat",
    },
    title: "Lepchajagat",
    country: "India",
    googleMapsLink: "https://maps.app.goo.gl/VVpjMWvA6fKmXCwu8",
    dates: "10 Mar, 2023 - 20 Mar, 2023",
    text: "Lepchajagat, a quaint village near Darjeeling, offers tranquil surroundings with dense forests and panoramic views of the Kanchenjunga range.",
  },
  {
    id: 14,
    img: {
      src: "https://images.unsplash.com/photo-1718889549552-2061c2eae040?w=1000&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Nnx8Q2hvcHRhJTIwVmFsbGV5fGVufDB8fDB8fHww",
      alt: "Chopta Valley",
    },
    title: "Chopta Valley",
    country: "India",
    googleMapsLink: "https://maps.app.goo.gl/MDrzc6mCN28dsGaN8",
    dates: "01 Apr, 2023 - 10 Apr, 2023",
    text: "Chopta, known as the 'Mini Switzerland of India,' is a picturesque hamlet in Uttarakhand, offering lush meadows and majestic views of the Himalayan ranges.",
  },
  {
    id: 15,
    img: {
      src: "https://media.istockphoto.com/id/1044860100/photo/living-root-bridge-of-meghalaya.jpg?s=612x612&w=0&k=20&c=S1k1f6uJitbFKvREr7sIHEbRQWQWxPLqQUrvkMnI5tE=",
      alt: "Mawlynnong Village",
    },
    title: "Mawlynnong Village",
    country: "India",
    googleMapsLink: "https://maps.app.goo.gl/HsTRBGVBGoKRcUhs6",
    dates: "15 May, 2023 - 25 May, 2023",
    text: "Mawlynnong in Meghalaya, acclaimed as the 'Cleanest Village in Asia,' is renowned for its cleanliness, living root bridges, and vibrant community life.",
  },
  {
    id: 16,
    img: {
      src: "https://mpholidays.com/wp-content/uploads/2023/01/Patalkot.jpg",
      alt: "Patalkot Valley",
    },
    title: "Patalkot Valley",
    country: "India",
    googleMapsLink: "https://maps.app.goo.gl/ig8hVMzpFfv6hQA97",
    dates: "01 Jun, 2023 - 10 Jun, 2023",
    text: "Patalkot, a hidden valley in Madhya Pradesh, is enveloped by dense forests and inhabited by indigenous tribes, offering a glimpse into untouched natural beauty and traditional lifestyles.",
  },
  {
    id: 17,
    img: {
      src: "https://thumbs.dreamstime.com/b/eco-park-trail-kaudia-kaudia-range-kanatal-entrance-to-eco-park-trail-kaudia-kaudia-range-kanatal-uttarakhand-253172249.jpg?w=992",
      alt: "Kanatal",
    },
    title: "Kanatal",
    country: "India",
    googleMapsLink: "https://maps.app.goo.gl/ZyDssJjzx3X6a7EC9",
    dates: "15 Jul, 2023 - 25 Jul, 2023",
    text: "Kanatal, a serene village in Uttarakhand, is surrounded by apple orchards and offers panoramic views of the Himalayas, making it a perfect offbeat destination for peace seekers.",
  },
  {
    id: 18,
    img: {
      src: "https://img.freepik.com/premium-photo/beautiful-om-beach-with-yellow-sand-gokarna-karnataka-india_431724-2980.jpg?w=900",
      alt: "Gokarna Beaches",
    },
    title: "Gokarna Beaches",
    country: "India",
    googleMapsLink: "https://maps.app.goo.gl/KdBvrvkyqsMAxfrs5",
    dates: "01 Aug, 2023 - 10 Aug, 2023",
    text: "Gokarna, a coastal town in Karnataka, boasts pristine and less commercialized beaches, offering tranquility and natural beauty away from the bustling tourist spots.",
  },
  {
    id: 19,
    img: {
      src: "https://c0.wallpaperflare.com/preview/197/267/754/ponmudi-india-scenic-beauty-nature.jpg",
      alt: "Ponmudi",
    },
    title: "Ponmudi",
    country: "India",
    googleMapsLink: "https://maps.app.goo.gl/4xGo6Kfn9F46EUSq8",
    dates: "15 Sep, 2023 - 25 Sep, 2023",
    text: "Ponmudi, a picturesque hill station in Kerala, is renowned for its lush green valleys, mist-laden hills, and meandering streams, offering a tranquil retreat for nature lovers.",
  },
];
